databases:
  - name: TeacherDocs
    plan: free
    region: oregon

services:
  - type: web
    plan: free
    region: oregon
    name: TeacherDocs
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/puma -C config/puma.rb"
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TeacherDocs
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
